### ISSUE TITLE
Cloud-init script generation

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#18]
This is split off from #16. We need a stand-alone or existing library that will generate cloud-init scripts for this provider.

**Comment by chuckha** [comment]
We can consider moving the existing code from CAPA to here that does this already

**Comment by moshloop** [comment]
I think while templates work, they are not ideal in the long term as evidenced by the kops migration away from templates to structs. 

There are golang structs for cloud-init that could be copied and pasted from here: https://github.com/moshloop/konfigadm/blob/master/pkg/cloud-init/types.go 

Another option is to import konfigadm as whole as it will enable other functionality such as embedding arbitrary files, multi-os  installation of prerequisites like  kubernetes/docker, coreos ignition support,

**Comment by chuckha** [comment]
Agreed, templates are definitely not ideal in the long term. I think they are a fine place to start and as the project expands and we determine the scope more clearly we can talk about alternative methods such as konfigadm. That being said, this library (bootstrap-provider-kubeadm) should be built so that changing out the script generation library is not painful.

**Comment by rudoi** [comment]
I think starting with what we have now in CAPA and refining makes the most sense to me, though I agree structs are the future. I'll take a swing at this. 😄 

/assign
/lifecycle active
