### ISSUE TITLE
Add support for overriding binaries in CABPK to avoid ansible usage

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#258]
/kind feature

context: CAPG CI job needs ansible currently and we would like to see if we can get away from it

Please see comments in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/177#discussion_r329114154

**Comment by detiber** [comment]
To elaborate on @dims comments, this is something that is less for a production-type use case, but is necessary for testing/CI use cases.

**Comment by chuckha** [comment]
Overriding binaries like...the ones cloud-init might call? @detiber or @dims can you please add more detail about this issue? I didn't find the linked comment to provide satisfactory detail.

**Comment by detiber** [comment]
@chuckha indeed, in general I'm thinking for e2e testing purposes we'd want to be able to override: `kubeadm`, `kubelet`, and `kubectl` at a minimum.

**Comment by chuckha** [comment]
I think an example would help me understand this a little more fully. In the abstract yes, I totally agree, but in practice, I'm having trouble thinking about what these overridden binaries would do especially in an e2e test. We would no longer be e2e testing since we're mocking out/overriding the binaries we'd actually be using. This might be some other kind of testing.

However, it seems entirely reasonable to me to use the `writefiles` section to drop binaries on the filesystem  that would be invoked with `runcmd`. Is there anything preventing overriding binaries today?

**Comment by detiber** [comment]
@chuckha the purpose here would be more around Kubernetes e2e testing using Cluster API rather than e2e testing of Cluster API itself. 

I think write_files doesn't currently fit the bill because it does not allow for writing files that are hosted remotely, only embedding the content directly into the cloud-init yaml.

**Comment by chuckha** [comment]
we had something like this in the aws quickstart.

write a script that gets remote binaries and installs them in the right spot
use BeforeCmds to run that script before kubeadm gets called. This feels possible with the tools we have today even if not exactly straight forward.

**Comment by ncdc** [comment]
@dims please see Chuck's comment above and let us know if you think there's any additional work we need to do. Thanks!

**Comment by dims** [comment]
@chuckha @ncdc that works!

**Comment by chuckha** [comment]
/close

@dims feel free to reopen if this ends up not working for you
